// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Plain `dotenv/config` only auto-loads `.env`, but `vercel env pull` writes
// to `.env.local` — load both explicitly, with `.env.local` taking priority,
// matching Next.js's own precedence.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // This installed Prisma version's config type only supports `url` and
    // `shadowDatabaseUrl` (no `directUrl`, despite some docs mentioning it).
    // Use the non-pooled connection string here: Prisma's migration engine
    // needs session-level features (advisory locks) that don't reliably
    // work through Neon/Vercel Postgres's pgbouncer pool. The app itself
    // (lib/db.ts) reads DATABASE_URL directly and keeps using the pooled
    // connection, which is what request-time queries should use.
    url: env("DATABASE_URL_UNPOOLED"),
  },
});
